jenkinsdata:
 build: jenkins-data
jenkinsmaster:
 image: testimtest
 volumes_from:
  - jenkinsdata
 ports:
  - "50000:50000"
  - "8080:8080"


jenkinsnginx:
 build: ./nginx/.
 ports:
  - "80:80"
 links:
  - jenkinsmaster:jenkinsmaster
